//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillsWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skills
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime FromDate { get; set; }
        public int Mark { get; set; }
        public bool StillInterestedIn { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
