//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillsAndTasks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skills
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    }
}
