//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillsAndTasks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int id { get; set; }
        public string task { get; set; }
        public string description { get; set; }
        public System.DateTime creation_date { get; set; }
        public int created_by { get; set; }
        public Nullable<int> assigned_to_user { get; set; }
        public Nullable<System.DateTime> modification_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public bool is_finished { get; set; }
        public string status { get; set; }
    }
}
